[package]
name = "python-macro"
version = "0.1.0"
authors = ["Sarah Stoltze <sstoltze@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
